name: Build and deploy storybook

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - update-ui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn

      - name: Build Ark Timer
        run: yarn build

      - name: Deploy ark timer
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
<<<<<<< HEAD
          FOLDER: build
          CLEAN: true
=======
          FOLDER: ./build
          CLEAN: true
>>>>>>> 712b6c1f059c6576660b9a78a5d9af0f03a4f6f9
